# Finally something to help the distribution.

PACKAGE=camlimages
RELEASE_TAG=camlimages_3_0_2
ANNOUNCE_FILE=Announce-3.0.2

tag:
	cvs rtag $(RELEASE_TAG) $(PACKAGE)

retag:
	cvs rtag -F -R $(RELEASE_TAG) $(PACKAGE)

announce:
	mail -n -s "New 3.0.2 release of the Caml Images library" \
	        caml-announce@inria.fr < $(ANNOUNCE_FILE) && \
        mail -n -s "New 3.0.2 release of the Caml Images library" \
	        caml-list@inria.fr < $(ANNOUNCE_FILE)

