#*********************************************************************#
#                                                                     #
#                          Caml Images                                #
#                                                                     #
#            François Pessaux, projet Cristal, INRIA Rocquencourt     #
#            Pierre Weis, projet Cristal, INRIA Rocquencourt          #
#            Jun Furuse, projet Cristal, INRIA Rocquencourt           #
#                                                                     #
#  Copyright 1999-2004,                                               #
#  Institut National de Recherche en Informatique et en Automatique.  #
#  Distributed only by permission.                                    #
#                                                                     #
#*********************************************************************#

#(* $Id: Makefile.in,v 1.11 2006/03/14 16:59:43 rousse Exp $ *)

bindir			= ${exec_prefix}/bin
libdir			= ${exec_prefix}/lib
livdir			= $(libdir)/liv
lablgtk2dir		= /usr/local/lib/ocaml/lablgtk2

INSTALL			= /usr/bin/install -c
CAMLC			= /usr/local/bin/ocamlc.opt
CAMLOPT			= /usr/local/bin/ocamlopt.opt
CAMLDEP			= /usr/local/bin/ocamldep.opt
CAMLLEX			= /usr/local/bin/ocamllex.opt
CAMLYACC		= /usr/local/bin/ocamlyacc
CAMLMKLIB		= /usr/local/bin/ocamlmklib

CAMLIMAGES_BASEDIRS	= corelib ppm bmp xvthumb jpeg tiff gif png xpm ps graphics freetype
CAMLIMAGES_GTK2DIR	= lablgtk2
WITH_CAMLIMAGES_BASE	= ci_core.cma graphics.cma ci_graphics.cma ci_freetype.cma ci_gif.cma ci_jpeg.cma ci_tiff.cma ci_bmp.cma ci_ppm.cma ci_png.cma ci_xvthumb.cma ci_xpm.cma ci_ps.cma
WITH_CAMLIMAGES_GTK2	= lablgtk.cma ci_lablgtk2.cma
WITH_UNIX		= unix.cma
DLLPATHS		= $(addprefix -dllpath ../../, \
			      $(CAMLIMAGES_BASEDIRS) \
			      $(CAMLIMAGES_GTK2DIR) \
			  )
COMPFLAGS		= $(addprefix -I ../../, \
			      $(CAMLIMAGES_BASEDIRS) \
			      $(CAMLIMAGES_GTK2DIR)\
			  ) \
			  -I $(lablgtk2dir)
LINKFLAGS		= $(COMPFLAGS) $(WITH_CAMLIMAGES_BASE) \
			  $(WITH_CAMLIMAGES_GTK2) \
                          -ccopt "-L$(lablgtk2dir)" \
			  -cclib "-llablgtk2 $(GTK2LIBS)" \
			  $(WITH_UNIX)

MODULES			= deficon mylazy cache livmisc gui jWidget seq tout \
			  enhance display viewer edge pathfind iconcap \
			  livshtype icon livsh scandir jpf liv
SRCS			= $(addsuffix .ml, $(MODULES))

all: byt opt

byt: liv.byt

liv.byt: $(SRCS:.ml=.cmo)
	$(CAMLC) -o liv.byt $(DLLPATHS) $(LINKFLAGS) $(SRCS:.ml=.cmo)

opt: liv

liv: $(SRCS:.ml=.cmx)
	$(CAMLOPT) -o liv $(LINKFLAGS:.cma=.cmxa) $(SRCS:.ml=.cmx)

install:: opt
	$(INSTALL) -d -m 755  $(LIVDIR)
	$(INSTALL) -m 755 liv $(BINDIR)
	$(INSTALL) -m 644 iconcap *.xpm *.jpg $(LIVDIR)

liv.ml:
	if test -f liv-jpf.ml; then \
	  ln -s liv-jpf.ml liv.ml; \
	else \
	  ln -s liv-org.ml liv.ml; \
	fi

enhance.cmo: enhance.ml
	$(CAMLC) -c $(COMPFLAGS) $<

enhance.cmx: enhance.ml
	$(CAMLOPT) -c $(COMPFLAGS) $<

clean::
	rm -f liv.byt liv

include ../../Makefile.rules
